INCLUDE globals.ink
Hello... #speaker:Dearil #portrait:default #player portrait:noxie_neutral #layout:right
I'm Mortis' assistant.
She might make me help you out...
I really don't want to...... 
No offense.........
->END